### ISSUE TITLE
Move this project to https://github.com/FasterXML/jackson-datatype-collections

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-datatype-pcollections#2]
@jroper Quick note: I am moving this project to an umbrella project, as per title. Move is mostly just to streamline release process slightly; overhead of a multi-module project is bit lower than having N sub-modules to release separately. One possible downside is that issue tracker is shared, so probably need to figure out a naming convention.

Anyway, thought I'll give a heads up. I will announce this on dev/user lists in a few days.

**Comment by jroper** [comment]
That sounds fine to me, completely agree with streamlining release processes.

**Comment by cowtowncoder** [comment]
Moved. Will close issue tracker here.
